version: "3.6"

services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ratings
        ports:
            - 6500:5432
